# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: James Guo’s Portfolio (@ZE3kr)
subtitle: ''
description: 'Original articles, videos and pictures relevant to technology, programming, and photography.'
keywords:
author: James Guo
language: en-US
language1: en-US
language2: zh-CN
timezone: 'Asia/Shanghai'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://ze3kr.com
permalink: :year/:month/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
  - _headers
  - _redirects
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-claudia

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo:
    # local: ~/sync/ZE3kr.com.git,main
    aliyun: ze3kr@bj1-aliyun.tloxygen.com:~/sync/ZE3kr.com.git,main
    us1-buyvm: ze3kr@us1-buyvm.tloxygen.com:~/sync/ZE3kr.com.git,main
    us1-aws: ze3kr@us1-aws.tloxygen.com:~/sync/ZE3kr.com.git,main
    jp1-aws: ze3kr@jp1-aws.tloxygen.com:~/sync/ZE3kr.com.git,main
    eu1-ovh: ze3kr@eu1-ovh.tloxygen.com:~/sync/ZE3kr.com.git,main

feed:
  enable: true
  type: atom
  path: feed.atom
  limit: false
  hub:

theme_config:
  title: James Guo (@ZE3kr)
  short: Portfolio
  short_cn: 作品集
  short2: ZE3kr
  widget_url: /categories/Portfolio/
  widget_filter: Portfolio
  piwik: 13

  # main menu navigation
  menu:
    Home: /
    About: /about/
    简体中文: https://guozeyu.com/
  # Archive: /archives

  license: |-
    <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh" target="_blank" rel="noopener nofollow">CC BY-SA 4.0</a>

  highlight: true

  widgets:
    - tag
    - category
    - profile

  links:
    - title: Zeus Wang
      url: https://zeus.wang
      domain: Zeus.Wang

  # social config
  social:
    twitter: ZE3kr
    instagram: ZE3kr
    github: ZE3kr
    email: james@tloxygen.com

  user:
    name: James Guo
    avatar: https://cdn.ze3kr.com/6T-behmofKYLsxlrK0l_MQ/4c3b6ecd-c2ad-42e7-0e3e-3077ef7de401/medium
    location: Saint Louis
    description: 🎯 Focusing
    footnotes: |-
      <a href="https://beian.miit.gov.cn/" target="_blank" class="has-text-grey">京ICP备17005542号-2</a>

  # documents: https://github.com/utterance/utterances
  # API config: https://utteranc.es/
  comment_utteranc:
    enable: true
    repo: ZE3kr/ZE3kr.com

  # documents: https://valine.js.org/quickstart.html
  comment_valine:
    enable: false
    appId:
    appKey:

  comment_disqus:
      enable: false
      url:  # the url of your website main domain like this https://xxx.xxx/
      name: # the short name in disqus

  # dark
  # light
  # user-can-set
  appearance: auto # Default value is auto

  # Miscellaneous
  favicon: https://cdn.ze3kr.com/6T-behmofKYLsxlrK0l_MQ/4c3b6ecd-c2ad-42e7-0e3e-3077ef7de401/thumbnail
  favicon_svg: /favicon.svg

  # picture of about page
  about_pic: https://cdn.ze3kr.com/6T-behmofKYLsxlrK0l_MQ/4c3b6ecd-c2ad-42e7-0e3e-3077ef7de401/extra

hide_posts:
  enable: true
  # Change the filter name to fit your need
  filter: hidden
  # Generators which you want to expose all posts (include hidden ones) to.
  # Common generators: index, tag, category, archive, sitemap, feed, etc.
  public_generators: ['tag', 'category', 'sitemap']
  noindex: false
